cabal-version:       3.0
name:                haskell-algorithm
version:             0.1.0.0
synopsis:            Algorithm implementations in Haskell
description:         Algorithm and data structure implementations in Haskell using TDD
license:             MIT
build-type:          Simple

common shared-properties
  default-language: GHC2021
  ghc-options: -Wall -Wno-missing-signatures

library
  import:           shared-properties
  hs-source-dirs:   src
  exposed-modules:
      BasicAlgorithms
    , Arrays
    , SearchAlgorithms
    , StacksAndQueues
    , Recursion
    , SortAlgorithms
    , Strings
    , LinkedLists
    , Trees
  build-depends:
      base >= 4.18 && < 5
    , array >= 0.5
    , containers >= 0.6

test-suite haskell-algorithm-test
  import:           shared-properties
  type:             exitcode-stdio-1.0
  hs-source-dirs:   test
  main-is:          Spec.hs
  other-modules:
      BasicAlgorithmsSpec
    , ArraysSpec
    , SearchAlgorithmsSpec
    , StacksAndQueuesSpec
    , RecursionSpec
    , SortAlgorithmsSpec
    , StringsSpec
    , LinkedListsSpec
    , TreesSpec
  build-depends:
      base >= 4.18 && < 5
    , array >= 0.5
    , containers >= 0.6
    , haskell-algorithm
    , hspec >= 2.0
    , hspec-discover >= 2.0
