<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="BasicAlgorithms.fs" />
    <Compile Include="Arrays.fs" />
    <Compile Include="SearchAlgorithms.fs" />
    <Compile Include="StacksAndQueues.fs" />
    <Compile Include="Recursion.fs" />
    <Compile Include="SortAlgorithms.fs" />
    <Compile Include="Strings.fs" />
    <Compile Include="LinkedLists.fs" />
    <Compile Include="Trees.fs" />
  </ItemGroup>
</Project>
