name: CI PHP

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'apps/php/**'
      - 'flake.nix'
      - 'flake.lock'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'apps/php/**'
      - 'flake.nix'
      - 'flake.lock'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Run tests
        run: nix develop .#php --command bash -c "cd apps/php && composer install && ./vendor/bin/phpunit"
