name: CI Rust

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'apps/rust/**'
      - '.github/workflows/ci-rust.yml'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'apps/rust/**'
      - '.github/workflows/ci-rust.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Run tests
        run: nix develop .#rust --command cargo test --manifest-path apps/rust/Cargo.toml
